const {mkdirSync, readdirSync, statSync, writeFileSync} = require('node:fs');
const {tmpdir} = require('node:os');
const {join, relative} = require('node:path');

const rawVersions = require('../versions');

const buildDocsDir = (version) => `docs/${version}`;
const buildRouteBasePath = (version) => `docs/${version}`;
const buildNavigationPath = (version) =>
  require.resolve(`../navigation/${version}.js`);

const loadSidebarConfig = (version) => {
  const {sidebar} = require(buildNavigationPath(version));

  if (!sidebar || typeof sidebar !== 'object') {
    throw new Error(`Missing sidebar config for version "${version}".`);
  }

  if (sidebar.mode !== 'manual' && sidebar.mode !== 'autogenerated') {
    throw new Error(
      `Unsupported sidebar mode "${sidebar.mode}" for version "${version}".`,
    );
  }

  if (
    sidebar.mode === 'autogenerated' &&
    Object.keys(sidebar).some((key) => key !== 'mode')
  ) {
    throw new Error(
      `Autogenerated sidebar config for version "${version}" must not define manual sidebar items.`,
    );
  }

  if (
    sidebar.mode === 'manual' &&
    !Object.keys(sidebar).some((key) => key !== 'mode')
  ) {
    throw new Error(
      `Manual sidebar config for version "${version}" must define at least one sidebar.`,
    );
  }

  return sidebar;
};

const buildManualSidebarPath = ({version, sidebar}) => {
  const {mode, ...manualSidebars} = sidebar;

  if (mode !== 'manual') {
    throw new Error(
      `Cannot build a manual sidebar module for non-manual version "${version}".`,
    );
  }

  const sidebarsDir = join(tmpdir(), 'open-kairos-docs-sidebars');
  const sidebarPath = join(sidebarsDir, `${version}.cjs`);

  mkdirSync(sidebarsDir, {recursive: true});
  writeFileSync(
    sidebarPath,
    `module.exports = ${JSON.stringify(manualSidebars, null, 2)};\n`,
  );

  return sidebarPath;
};

const normalizeVersion = ({
  version,
  introDocId,
  fallbackDocId,
  quickStartDocId,
}) => ({
  slug: version,
  label: version,
  docsDir: buildDocsDir(version),
  routeBasePath: buildRouteBasePath(version),
  sidebar: loadSidebarConfig(version),
  introDocId,
  fallbackDocId,
  quickStartDocId,
});

const versions = rawVersions.map(normalizeVersion);
const latestVersion = versions.at(-1)?.slug;

const collectDocPaths = (rootDir, currentDir = rootDir) =>
  readdirSync(currentDir)
    .flatMap((entry) => {
      const absolutePath = join(currentDir, entry);
      const stats = statSync(absolutePath);

      if (stats.isDirectory()) {
        return collectDocPaths(rootDir, absolutePath);
      }

      if (!entry.endsWith('.md') && !entry.endsWith('.mdx')) {
        return [];
      }

      const relativePath = relative(rootDir, absolutePath).replace(
        /\.(md|mdx)$/u,
        '',
      );

      return [relativePath.replace(/\\/gu, '/')];
    })
    .sort((left, right) => left.localeCompare(right, 'en'));

const buildDocPathManifest = (configuredVersions) =>
  configuredVersions.reduce(
    (manifest, version) => ({
      ...manifest,
      [version.slug]: collectDocPaths(version.docsDir),
    }),
    {},
  );

const buildSearchContexts = (configuredVersions) =>
  configuredVersions.map(({label, routeBasePath}) => ({
    label,
    path: routeBasePath,
  }));

const createDocsPlugins = (configuredVersions) =>
  configuredVersions.map((version) => [
    '@docusaurus/plugin-content-docs',
    {
      ...(version.slug === latestVersion
        ? {}
        : {id: `version-${version.slug.replace(/[^a-z0-9]+/giu, '-')}`}),
      path: version.docsDir,
      routeBasePath: version.routeBasePath,
      ...(version.sidebar.mode === 'manual'
        ? {
            sidebarPath: buildManualSidebarPath({
              version: version.slug,
              sidebar: version.sidebar,
            }),
          }
        : {}),
    },
  ]);

const createRegistryConfig = () => {
  const latestVersionEntry = versions.at(-1);

  return {
    customFields: {
      versions: versions.map(
        ({slug, label, routeBasePath, introDocId, fallbackDocId}) => ({
          slug,
          label,
          routeBasePath,
          introDocId,
          fallbackDocId,
        }),
      ),
      latestVersion,
      docsIntroPath: `/docs/${latestVersionEntry.slug}/${latestVersionEntry.introDocId}`,
      docsQuickStartPath: `/docs/${latestVersionEntry.slug}/${latestVersionEntry.quickStartDocId}`,
      docPathManifest: buildDocPathManifest(versions),
    },
    docsPlugins: createDocsPlugins(versions),
    search: {
      docsRouteBasePath: versions.map(({routeBasePath}) => routeBasePath),
      searchContextByPaths: buildSearchContexts(versions),
    },
  };
};

module.exports = createRegistryConfig;
