name: 🚀 Deploy Selected Docs Branch
run-name: Deploy docs for ${{ github.ref_name }}

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    uses: ./.github/workflows/publish-branch-runner.yml
    with:
      target_branch: ${{ github.ref_name }}
    secrets: inherit
